### ISSUE TITLE
URL ignored during contact save

### ISSUE THREAD

**Issue by Bramzor** [apache/cordova-plugin-contacts#174]
Im trying to save a contact which works for most information but if I try to add an URL to the contact it just ignores the update without an error.

For example:

```
contact.urls.push(new ContactField("SomeValue", "http://www.example.com"))
console.log(contact)
let result = await contact.save()
console.log(result)
```

Print before save():
` ... "urls":[{"type":"SomeValue","value":"http://www.example.com"}] ... `
After contact.save():
` ... "urls":null ...`

Any idea why my input is ignored?

**Comment by Bramzor** [comment]
I did create a test app to show the issue: https://github.com/Bramzor/ionic-native-contacts-tests

**Comment by sava999** [comment]
Hi @Bramzor I got here from your job post on UpWork 😄 

Maybe this is your problem: https://github.com/apache/cordova-plugin-contacts/blob/master/src/ios/CDVContact.m#L1006 looking at this comment this is not available on iOS (not sure is that true I am not native iOS dev) but looking at ReactNative implementation it should be possible, check this: https://github.com/rt2zz/react-native-contacts/blob/master/ios/RCTContacts/RCTContacts.m#L211 maybe you can fork this plugin and reuse code from ReactNative implementation.

Anyway, it looks like this is not implemented and probably it will not be since plugin is deprecated.

**Comment by janpio** [comment]
(Just a side note: Don't let the deprecation notice stop you from fixing bugs here and sending a Pull Request - we will sure find a way to integrate those here or in a fork)

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
