### ISSUE TITLE
iOS 13 note field of contact is null

### ISSUE THREAD

**Issue by crascher** [apache/cordova-plugin-contacts#218]
In iOS 13 I am not able to retrieve the note field.
I am able to see the note field, but not able to read it.

Does anyboday has a fix for this problem that seems only to occur for iOS 13?

**Comment by crascher** [comment]
I found the reason: https://9to5mac.com/2019/06/05/ios-13-contacts-notes/

**Comment by breautek** [comment]
I don't doubt this but I wish I could find an official link like from the apple docs or something that explicitly states this change so that we can add a quirk note with a reference. But I'm failing to find such a thing and it looks like Apple just literally made a breaking change with absolutely no heads up as far as I can tell.

**Comment by timbru31** [comment]
We are archiving this repository following [Apache Cordova's Deprecation Policy](https://cordova.apache.org/deprecation_policy.html). We will not continue to work on this repository. Therefore all issues and pull requests are being closed. Thanks for your contribution.
